import { useNavigate } from 'react-router-dom'
import { useStore } from '../../../mock/store'
import { useUI } from '../../../app/ui'
import type { Study } from '../../../mock/types'

/** Zoom link supplied by the team, not generated by the app (workflow step 39). */
const MOCK_ZOOM_URL = 'https://zoom.us/j/9876543210'

/** Join Call opens the mock Zoom link; in-person sessions open directions. */
export function openSession(study: Study) {
  const inPerson = study.type === 'in_person' || study.type === 'in_person_group'
  if (inPerson) {
    const address = study.locations?.find((l) => l.id === study.booking?.locationId)?.address ?? study.locations?.[0]?.address
    window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address ?? '')}`, '_blank', 'noopener,noreferrer')
    return
  }
  window.open(MOCK_ZOOM_URL, '_blank', 'noopener,noreferrer')
}

/** Detail screen actions, derived from status like everything else. */
export function useDetailActions(study?: Study, onLocations?: () => void) {
  const navigate = useNavigate()
  const { completeStudy, toast } = useStore()
  const { openMatchScore } = useUI()
  const inPerson = study?.type === 'in_person' || study?.type === 'in_person_group'

  const go = (suffix = '') => navigate(`/studies/${study?.id}${suffix}`)

  const primary = () => {
    if (!study) return
    switch (study.status) {
      case 'available':
      case 'invited_to_apply':
        // In-person studies show their locations first (PRD 6.8).
        if (inPerson && study.locations?.length && onLocations) onLocations()
        else go('/screener')
        break
      case 'draft': go('/screener'); break
      case 'invited_to_schedule': go('/schedule'); break
      case 'invited_to_complete':
        if (study.type === 'diary') go('/diary')
        else if (study.type === 'survey') go('/survey')
        else go('/schedule')
        break
      case 'scheduled': go('/pin'); break
      case 'pin_confirmed': completeStudy(study.id); toast('Study completed, payment on its way'); break
      case 'paid': go('/rate'); break
      default: break
    }
  }

  const secondary = () => {
    if (!study) return
    if (study.status === 'scheduled' || study.status === 'pin_confirmed') openSession(study)
    else go()
  }

  return {
    primary,
    secondary,
    matchScore: openMatchScore,
    // Get Support opens a ticket with this study prefilled in the subject.
    getSupport: () =>
      navigate(`/support/contact?study=${encodeURIComponent(study?.title ?? '')}`),
  }
}
